### ISSUE TITLE
Build fails without blkid devel 

### ISSUE THREAD

**Issue by gador** [mhogomchungu/cryfs-gui#1]
Hi,

follwoing your build instructions cmake finishes without errors but actually compiling with make raises the following:

`fatal error: blkid/blkid.h: No such file or directory`

Installing the missing blkid devel package fixes the problem and cryfs-gui compiles.

Could you add the blkid devel package to the list of requirements?

Thanks, Florian

**Comment by mhogomchungu** [comment]
cryfs-gui has no dependency on blkid.

This project is stripped down version of another project of mine and it looks like the header that generated that error needs to be updated to remove the line that generated that error.

Do you still have the texts that were generated when the build error occurred? They contain information about where the line to be removed is.

**Comment by mhogomchungu** [comment]
Below commit fixes the problem.

https://github.com/mhogomchungu/cryfs-gui/commit/cd1ab6a767cda21786b38e69700d8ebde5f2f030

**Comment by gador** [comment]
I just removed the blkid-dev package again to get the error message:

```

Scanning dependencies of target cryfs
...
Building CXX object CMakeFiles/cryfs.dir/src/utility.cpp.o
cryfs-gui/src/utility.cpp:39:25: fatal error: blkid/blkid.h: No such file or directory
compilation terminated.
```

Hope that helps.

**Comment by mhogomchungu** [comment]
I found the line by renaming "blkid.h" file to something else before trying to compile.

Thanks for your report.
