### ISSUE TITLE
Add feature to choose where to mount in GUI would be nice

### ISSUE THREAD

**Issue by gador** [mhogomchungu/cryfs-gui#2]
Just a thought to improve:

Right now, you can choose the prefix of the mounted directory. 
However it would be awesome, if you could choose the mountpoint of every encrypted volume separately and through the GUI.

**Comment by mhogomchungu** [comment]
what is your usecase?

do you also prefer your custom mount point to be remember for every volume that uses a custom path?

keeping re changing the mount path everytime a volume is to be mounted will get annoying sooner or later.

**Comment by mhogomchungu** [comment]
Just made a commit that i think has a solution to what you are suggesting.

First,the GUI now has an editable field that you can modify and add path you want to be used as a mount point.

Second,when you add a volume to the favorites list,the mount point field  nows uses a full mount point path and you can change the default value to any value of your choice.The default value or your proffered path will be used everytime the volume is mounted from the favorites list.

I am closing this one as "fixed" but feel free to comment if you think anything can be improved.

**Comment by gador** [comment]
Awesome! That is exactly what I was looking for!

**Comment by wkarl** [comment]
Perfect, thanks for adding this feature!

**Comment by mhogomchungu** [comment]
Thanks for the reminder,i planned to document this feature in the main page after i made the latest release but i somehow forgot about it.

You should not have come this far to know about this ability.
