### ISSUE TITLE
Packaged version number wrong

### ISSUE THREAD

**Issue by smessmer** [mhogomchungu/cryfs-gui#3]
I installed the current (version 1.3.1) Ubuntu 16.04 .deb package using apt-get.
Afterwards, I ran cryfs-gui and ran "Check Updates" from the menu.
It shows me, I'm running 1.0.0 and should update to 1.3.1.

I also tried downloading and installing the .deb package manually - same result.

**Comment by mhogomchungu** [comment]
Can you provide the url of the package you downloaded?

Everything works fine here using ubuntu 16.04.

![screenshot_20160728_184728](https://cloud.githubusercontent.com/assets/3496115/17219423/02e34a08-54f4-11e6-87a6-50ce5f42215f.png)

**Comment by smessmer** [comment]
Ok looks like it was my fault. I had cryfs-gui 1.0.0 running on this machine in the background and when I started it after installing, it didn't start the new one but fetched the old one from the background...

I'm now proud user of cryfs-gui 1.3.1, thanks :)
