### ISSUE TITLE
Weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by pehlm** [mhogomchungu/cryfs-gui#5]
Hi!
Thanks for a great project! I'm on Ubuntu 16.04 and wants to be able to use your apt repository but when I trying to use it in Synaptic the output is:
"W: http://download.opensuse.org/repositories/home:/mhogomchungu/xUbuntu_16.04/Release.gpg: Signature by key 1684885B6FFA57BD2576354F007312F085D89AA2 uses weak digest algorithm (SHA1)"
This is because of the apt SHA1 removal. Can you please update the keys so it is possible to use your apt repository.
Regards

**Comment by mhogomchungu** [comment]
i also have ubuntu 16.04 and i am aware of this problem.

I build binary packages using opensuse build service(OBS)[1] and the solution has to come from their end. Other people have reported the problem and a ticket for it is here[2].

I do not touch these binaries,the source code is taken directly from github,build by OBS and hosted by them for distribution by them also.

I think the only thing i can do is wait until they fix it.

[1] https://build.opensuse.org/package/show/home:mhogomchungu/cryfs-gui

[2] https://github.com/openSUSE/obs-sign/issues/5

**Comment by pehlm** [comment]
Ok, thank you for your quick answer, and we hope they will fix it then.

**Comment by mhogomchungu** [comment]
closing this one as "fixed".

cryfs-gui is no more as its moved to SiriKali[1] and you can get working SiriKali packages without the problem from here[2]

[1] https://mhogomchungu.github.io/sirikali

[2] http://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=sirikali
